# site settings
title: Abdelrahman
subtitle: Zayed
email: abdel.zayed.1@gmail.com
description: 'PhD student in Computer science'
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city:
state:
zip_code:
country:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/AbdelrahmanZayed
# gitlab_url:
# googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/abdelrahman-zayed-669382103/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
